version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "dbampalikis"
      - "jbygdell"
      - "pontus"
      - "jonandernovella"
      - "blankdots"
      - "dtitov"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "dbampalikis"
      - "jbygdell"
      - "pontus"
      - "jonandernovella"
      - "blankdots"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "dbampalikis"
      - "jbygdell"
      - "pontus"
      - "jonandernovella"
      - "blankdots"
