version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
    - "dbampalikis"
    - "jbygdell"
    - "pontus"
    - "jonandernovella"
    - "blankdots"
    - "dtitov"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
    - "dbampalikis"
    - "jbygdell"
    - "pontus"
    - "jonandernovella"
    - "blankdots"
