version: "2.4"
services:
  ingest:
    command: sda-ingest
    container_name: ingest
    env_file: ./env.ingest
    image: neicnordic/sda-pipeline:latest
    volumes:
      - ./config.yaml:/config.yaml
      - ./:/dev_utils/
      - archive:/tmp
    mem_limit: 1024m
    restart: always
  verify:
    command: sda-verify
    container_name: verify
    env_file: ./env.verify
    image: neicnordic/sda-pipeline:latest
    volumes:
      - ./config.yaml:/config.yaml
      - ./:/dev_utils/
      - archive:/tmp
    mem_limit: 256m
    restart: always
  finalize:
    command: sda-finalize
    container_name: finalize
    env_file: ./env.finalize
    image: neicnordic/sda-pipeline:latest
    volumes:
      - ./config.yaml:/config.yaml
      - ./:/dev_utils/
    mem_limit: 64m
    restart: always
  mapper:
    command: sda-mapper
    container_name: mapper
    env_file: ./env.mapper
    image: neicnordic/sda-pipeline:latest
    volumes:
      - ./config.yaml:/config.yaml
      - ./:/dev_utils/
    mem_limit: 64m
    restart: always
  interceptor:
    command: sda-intercept
    container_name: intercept
    env_file: ./env.intercept
    image: neicnordic/sda-pipeline:latest
    volumes:
      - ./config.yaml:/config.yaml
      - ./:/dev_utils/
    mem_limit: 64m
    restart: always

volumes:
     archive:
